### PR TITLE
Add Keynote Pages

### PR DESCRIPTION
**Pull request by NTCoding**

### CODE REVIEW

**Comment by simplytalking** [comment]
I have created an announcement page in what seems like the right place /announcements/keynotes/2019/02/18/launching-spa-2019-keynotes.md

I have enabled the news page in the _config.yml file (in both places)

I restarted my local server.

It looks to me like I should be adding the link and post title to either the news.md page or to some other page but I really have no idea what I should be doing.

Can some kind soul point me in the right direction? 

I will also update the build notes for the site once I understand this.

many thanks, Jason

**Comment by simplytalking** [comment]
Nick I have done some fixing up of your keynote pages - Simon gave me a talk summary, I got a better picture from Rachel (which I am just uploading now) and I linked those pages to the index page and the announcement page.

**Comment by simplytalking** [comment]
Rachel's latest picture is uploaded

**Comment by NTCoding** [comment]
Homepage, keynote speaker pages, and announcement pages all look good. Great job @simplytalking

**Comment by simplytalking** [comment]
Does the news page work?

**Comment by NTCoding** [comment]
Yes it works @simplytalking

**Comment by NTCoding** [comment]
screenshot 2019-02-18 at 19 43 27

**Comment by simplytalking** [comment]
cool! :)

**Pull request merged**
