### PR TITLE
Added sponsor packages prices and "sponsor a speaker" option.

### PR DESCRIPTION
**Pull request by gasproni**
I've added the new prices for 2019 (to add 20% to each of the below ones):
- for general sponsorship £1,450 (1250 + 200)
- for lunch packages £950 (750 + 200) to keep it under £1000 as agreed before.
- for dinner packages £1250 (1000 + 250)
I've also added the "sponsor a speaker" package with a "contact us" for the price, as I guess it depends on the travel costs of the speakers.
Feedback appreciated.

### CODE REVIEW

**Comment by simplytalking** [comment]
I still would like to go with offering the corporate tickets into some of the sponsorship packages:

Conference Sponsorship - £1,450 + 20% VAT (Three Available)
    Two corporate tickets at a 20% discount

Dinner Package - £1,250 + 20% VAT (Two Available)
    Two corporate tickets at a 15% discount

Lunch Package - £1,000 + 20% VAT (Three Available)
    One corporate tickets at a 15% discount


Suggestions?

**Comment by simplytalking** [comment]
I should have said I don't think we need to bump the prices much because we are offering corporate tickets which have just increased the price to then discount the price. So my suggestion was just to raise the lunch package to 1,000 and leave the other two as you priced them.

**Comment by simplytalking** [comment]
Agree with you on the unlimited conference packages.

I was at MonkiGras last week and their whole two day conference is on accessibility. 

They have an accessibility and an inclusion sponsorship packages and they were their most popular packages. 

Could we do that for SPA? We have discussed the ideas of doing those already. Take two versions of the general sponsors - we have to decide what it would pay for? I assume captioning - if that is the case then we should find out how much captioning is likely to cost. I could reach out to the firm that did the work for MonkiGras.

For the inclusion package then it would be to cover the cost of doing inclusion better: maybe to bring all our inclusion tickets from £99 to £0?

**Comment by simplytalking** [comment]
We need to make a decision on 
1) inclusion of discounted corporate tickets
2) pricing
then we can get them up on the site.
the accessibility and inclusivity sponsorships can come in the following days

**Comment by gasproni** [comment]
I've bumped up the lunch package prices to match the dinner ones.

**Comment by gasproni** [comment]
I'm going to merge this pull request as we are late, and we need to take a decision now.

**Pull request merged**
