### PR TITLE
CfP launch 2019 3

### PR DESCRIPTION
**Pull request by simplytalking**
This is the rebased CfP-update-1 that had become unwieldy with over 15 commits. Hopefully the commits are now clearer about what they are doing. But refer to theCfP-update-1 (#67) comments if you want to follow the long-winded process of getting this ready

### CODE REVIEW

**Comment by simplytalking** [comment]
Removed favicon1.ico

I am quite happy to have a go at clarifying the info architecture. Readme.md has my attempt.

I agree the sponsorship should be pulled into another PR and will do that.

I have changed the titles.

What do I do with the old pull request on the old branch we were working on?

**Comment by simplytalking** [comment]
The favicon.ico now displays

**Comment by annashipman** [comment]
This looks good to me. Thanks for making those changes. Feel free to merge.

Great! Looking forward to promoting the CFP.

**Comment by annashipman** [comment]
We can close the old one, I will do that.

**Pull request merged**
